- name: install and run nginx
  hosts: backend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  # - name: start the nginx
  #   ansible.builtin.service:
  #     name: nginx
  #     state: started
  #     enable: yes
  - name: Reload service nginx, in all cases
    ansible.builtin.systemd_service:
     name: nginx
     state: reloaded
     






      

      






  