- name: install and run nginx
  hosts: backend
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start the nginx
    ansible.builtin.systemd:
      name: nginx
      state: started
      enable: yes
      

      






  