- name: install the packages
  hosts: backend
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.package:
     msg: "{{ item }}"
     state: install
    loop:
     - gcc
     - git
     - mysql
     - zip
     



